### ISSUE TITLE
Shouldn't A.SolveWith(b) return a matrix?

### ISSUE THREAD

**Issue by hizzlehoff** [darkdragon-001/LightweightMatrixC-#8]
Thanks for the great work.

I am curious why "A.SolveWith(b);" doesn't return a matrix?

Surely if A and B are matrices than X in "A*X=B" should also be matrix?

**Comment by darkdragon-001** [comment]
`x` and `b` are vectors. You are right, there should be an additional check for `v.cols == 1`.

This is the standard procedure to solve linear equations:
`a11 * x1 + a12 * x2 = b1`
`a21 * x1 + a22 * x2 = b2`
